CREATE TABLE processes (
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
   `flow_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '流程id',
     `process_name` varchar(45) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '步骤名称',
     `limit_time` int(11) NOT NULL DEFAULT '0' COMMENT '限定时间,单位秒',
     `type` varchar(32) COLLATE utf8mb4_bin NOT NULL DEFAULT 'operation' COMMENT '流程图显示操作框类型',
     `icon` varchar(64) COLLATE utf8mb4_bin DEFAULT '' COMMENT '流程图显示图标',
     `process_to` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
     `style` text COLLATE utf8mb4_bin,
     `style_color` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '#78a300',
     `style_height` smallint(6) NOT NULL DEFAULT '30',
     `style_width` smallint(6) NOT NULL DEFAULT '30',
     `position_left` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '100px',
     `position_top` varchar(128) COLLATE utf8mb4_bin NOT NULL DEFAULT '200px',
     `position` smallint(6) NOT NULL DEFAULT '1' COMMENT '步骤位置：1正常步骤2：转入子流程0：第一步 当为2时 child_flow_id child_after child_back_process 可设置',
     `child_flow_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '子流程id',
     `child_after` tinyint(4) NOT NULL DEFAULT '2' COMMENT '子流程结束后 1.同时结束父流程 2.返回父流程',
     `child_back_process` bigint(20) NOT NULL DEFAULT '0' COMMENT '子流程结束后返回父流程进程',
     `description` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '' COMMENT '步骤描述',
  created_at datetime(3) NOT NULL,
  updated_at datetime(3) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_processes_created_at (created_at),
  KEY idx_processes_updated_at (updated_at)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
